// <auto-generated/>
// 
// This file is generated using ClangSharpPInvokeGenerator.
// Please refrain from manual modifications.
// If changes are necessary, modify generate.ps1 and regenerate the file.
//

namespace SharpLSL.Interop
{
    public enum lsl_transport_options_t
    {
        transp_default = 0,
        transp_bufsize_samples = 1,
        transp_bufsize_thousandths = 2,
        _lsl_transport_options_maxval = 0x7f000000,
    }
}
