//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ClangSharpPInvokeGenerator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1591

namespace SharpLSL.Interop
{
    public enum lsl_transport_options_t
    {
        transp_default = 0,
        transp_bufsize_samples = 1,
        transp_bufsize_thousandths = 2,
        _lsl_transport_options_maxval = 0x7f000000,
    }
}
