//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ClangSharpPInvokeGenerator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpLSL.Interop
{
    public enum lsl_error_code_t
    {
        lsl_no_error = 0,
        lsl_timeout_error = -1,
        lsl_lost_error = -2,
        lsl_argument_error = -3,
        lsl_internal_error = -4,
        _lsl_error_code_maxval = 0x7f000000,
    }
}
