// <auto-generated/>
// 
// This file is generated using ClangSharpPInvokeGenerator.
// Please refrain from manual modifications.
// If changes are necessary, modify generate.ps1 and regenerate the file.
//

namespace SharpLSL.Interop
{
    public enum lsl_channel_format_t
    {
        cft_float32 = 1,
        cft_double64 = 2,
        cft_string = 3,
        cft_int32 = 4,
        cft_int16 = 5,
        cft_int8 = 6,
        cft_int64 = 7,
        cft_undefined = 0,
        _cft_maxval = 0x7f000000,
    }
}
