// <auto-generated/>
// 
// This file is generated using ClangSharpPInvokeGenerator.
// Please refrain from manual modifications.
// If changes are necessary, modify generate.ps1 and regenerate the file.
//
