// This file is auto generated by using ClangSharpPInvokeGenerator.
// Please DO NOT modify it manully. Instead, modify SharpLSL.rsp and
// re-run ClangSharpPInvokeGenerator in cmd.exe:
//     ClangSharpPInvokeGenerator @SharpLSL.rsp
// or in PowerShell:
//     ClangSharpPInvokeGenerator "@SharpLSL.rsp"
