<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup Label="Build">
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>

  <ItemGroup Label="Package References">
    <PackageReference Include="SharpLSL.Native.linux-arm64" Condition="$([MSBuild]::IsOsPlatform('Linux'))" />
    <PackageReference Include="SharpLSL.Native.linux-x64" Condition="$([MSBuild]::IsOsPlatform('Linux'))" />
    <PackageReference Include="SharpLSL.Native.osx" Condition="$([MSBuild]::IsOsPlatform('OSX'))" />
    <PackageReference Include="SharpLSL.Native.win-arm64" Condition="$([MSBuild]::IsOsPlatform('Windows'))" />
    <PackageReference Include="SharpLSL.Native.win-x64" Condition="$([MSBuild]::IsOsPlatform('Windows'))" />
    <PackageReference Include="SharpLSL.Native.win-x86" Condition="$([MSBuild]::IsOsPlatform('Windows'))" />
  </ItemGroup>

  <ItemGroup Label="Project References">
    <ProjectReference Include="..\..\src\SharpLSL\SharpLSL.csproj" />
  </ItemGroup>
</Project>
