//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ClangSharpPInvokeGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1591
