// <auto-generated/>
// 
// This file is generated using ClangSharpPInvokeGenerator.
// Please refrain from manual modifications.
// If changes are necessary, modify generate.ps1 and regenerate the file.
//

namespace SharpLSL.Interop
{
    public enum lsl_processing_options_t
    {
        proc_none = 0,
        proc_clocksync = 1,
        proc_dejitter = 2,
        proc_monotonize = 4,
        proc_threadsafe = 8,
        proc_ALL = 1 | 2 | 4 | 8,
        _proc_maxval = 0x7f000000,
    }
}
